image: node:latest

stages:
  - build
  - lint
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

linting:
  stage: lint
  script: yarn lint

testing:
  stage: test
  script: yarn test
